apiVersion: v1
kind: Service
metadata:
  labels:
    glusterfs: heketi-deployment
    heketi: deployment
  name: heketi-endpoint
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    glusterfs: heketi-pod
    heketi: pod
  sessionAffinity: None
  type: LoadBalancer